const catalogProduct = [
    {
        id: '1',
        name: 'Ящик Optima',
        price: 72,
        depth: '34 см.',
        width: '32 см.',
        height: '24,5 см.',
        spaciousness: '27 л.',
        material: 'берёза',
        coating: 'восковый лак',
        description: `Ящики модульные для детской! Компактно вместят детские игрушки, материалы для творчества,
         книг и многое другое.Они легко и просто становятся друг на друга, и не занимают много место!<br><br>
        В нашей палитре вы обязательно подберете нужные цвета ящиков в вашу детскую, а меловая табличка подскажет,
        что где лежит!<br>`,
        img: './img/optima.jpg',
        img1: './img/optima.jpg',
        img2: './img/img_product/C4zuU3NFOCM.jpg',
        img3: './img/img_product/r7VvMGAQluc.jpg',
        img4: './img/img_product/m7qbZc8EfJA.jpg',
        category: 'Ящики для игрушек',
        subcategory_1: 'modular',
        subcategory_2: 'frame'
    },
    {
        id: '2',
        name: 'Ящик Maxi',
        price: 80,
        depth: '34 см.',
        width: '32 см.',
        height: '37 см.',
        spaciousness: '40 л.',
        material: 'берёза',
        coating: 'восковый лак',
        description: `Ящики модульные для детской! Компактно вместят детские игрушки, материалы для творчества,
         книг и многое другое.Они легко и просто становятся друг на друга, и не занимают много место!<br><br>
        В нашей палитре вы обязательно подберете нужные цвета ящиков в вашу детскую, а меловая табличка подскажет,
        что где лежит!<br>`,
        img: './img/maxi.jpg',
        img1: './img/maxi.jpg',
        img2: './img/img_product/69514036_355147265365419_7233966578354388877_n.jpg',
        img3: './img/img_product/RT_E_kWPzWA.jpg',
        img4: './img/img_product/-TUAkI9kkoI.jpg',
        category: 'Ящики для игрушек',
        subcategory_1: 'modular',
        subcategory_2: 'frame'
    },
    {
        id: '3',
        name: 'Крышка для ящиков',
        price: 26,
        depth: '34 см.',
        width: '32 см.',
        height: '5 см.',
        spaciousness: '-',
        material: 'берёза',
        coating: 'восковый лак',
        description: `Крышка становятся на ящики: mini, optima, maxi`,
        img: './img/krisha.jpg',
        img1: './img/krisha.jpg',
        img2: './img/img_product/03V4cIQXia4.jpg',
        img3: './img/img_product/IUm_j8RYeC4.jpg',
        img4: './img/img_product/h3l2DfI_rNE.jpg',
        category: 'Ящики для игрушек',
        subcategory_1: 'cap',
        subcategory_2: 'no_slate_cap'
    },
    {
        id: '4',
        name: 'Ящик Mini',
        price: 60,
        depth: '34 см.',
        width: '32 см.',
        height: '12,5 см.',
        spaciousness: '13 л.',
        material: 'берёза',
        coating: 'восковый лак',
        description: `Ящики модульные для детской! Компактно вместят детские игрушки, 
        материалы для творчества, книг и многое другое.Они легко и просто ...`,
        img: './img/mini.png',
        img1: './img/mini.png',
        img2: './img/img_product/отобр8.jpg',
        img3: './img/img_product/DSC02603.jpg',
        img4: './img/img_product/69514036_355147265365419_7233966578354388877_n.jpg',
        category: 'Ящики для игрушек',
        subcategory_1: 'modular',
        subcategory_2: 'no_frame'
    },
    {
        id: '5',
        name: 'Ящик Mini с делениями',
        price: 66,
        depth: '34 см.',
        width: '32 см.',
        height: '12,5 см.',
        spaciousness: '13 л.',
        material: 'берёза',
        coating: 'восковый лак',
        description: `Ящики модульные для детской! Компактно вместят детские игрушки, 
        материалы для творчества, книг и многое другое.Они легко и просто ...`,
        img: './img/minidel.jpg',
        img1: './img/minidel.jpg',
        img2: './img/img_product/DSC_93191567.jpg',
        img3: './img/img_product/DSC02603.jpg',
        img4: './img/img_product/-TUAkI9kkoI.jpg',
        category: 'Ящики для игрушек',
        subcategory_1: 'modular',
        subcategory_2: 'no_frame'
    },
    {
        id: '6',
        name: 'Крышка для Mini',
        price: 14,
        depth: '34 см.',
        width: '32 см.',
        height: '1 см.',
        spaciousness: '-',
        material: 'берёза',
        coating: 'восковый лак',
        description: `Крышка для ящика "Mini с делениями"`,
        img: './img/krishmini.jpg',
        img1: './img/krishmini.jpg',
        img2: './img/krishmini.jpg',
        img3: './img/krishmini.jpg',
        img4: './img/krishmini.jpg',
        category: 'Ящики для игрушек',
        subcategory_1: 'cap',
        subcategory_2: 'slate_cap'
    },
    {
        id: '7',
        name: 'Ящик Huge',
        price: 70,
        depth: '60 см.',
        width: '60 см.',
        height: '15 см.',
        spaciousness: '48 л.',
        material: 'берёза',
        coating: 'восковый лак',
        description: `Ящики модульные для детской! Компактно вместят детские игрушки, 
        материалы для творчества, книг и многое другое.Они легко и просто ...`,
        img: './img/huge.jpg',
        img1: './img/huge.jpg',
        img2: './img/huge.jpg',
        img3: './img/huge.jpg',
        img4: './img/huge.jpg',
        category: 'Ящики для игрушек',
        subcategory_1: 'big',
        subcategory_2: 'frame'
    },
    {
        id: '8',
        name: 'Ящик Huge с делениями',
        price: 80,
        depth: '60 см.',
        width: '60 см.',
        height: '15 см.',
        spaciousness: '48 л.',
        material: 'берёза',
        coating: 'восковый лак',
        description: `Ящики модульные для детской! Компактно вместят детские игрушки, 
        материалы для творчества, книг и многое другое.Они легко и просто ...`,
        img: './img/hugedel.jpg',
        img1: './img/hugedel.jpg',
        img2: './img/hugedel.jpg',
        img3: './img/hugedel.jpg',
        img4: './img/hugedel.jpg',
        category: 'Ящики для игрушек',
        subcategory_1: 'big',
        subcategory_2: 'frame'
    },
    {
        id: '9',
        name: 'Крышка для Huge',
        price: 26,
        depth: '60 см.',
        width: '60 см.',
        height: '1 см.',
        spaciousness: '-',
        material: 'берёза',
        coating: 'восковый лак',
        description: `Крышка для ящика "Huge с делениями"!!!`,
        img: './img/krishhuge.jpg',
        img1: './img/krishhuge.jpg',
        img2: './img/krishhuge.jpg',
        img3: './img/krishhuge.jpg',
        img4: './img/krishhuge.jpg',
        category: 'Ящики для игрушек',
        subcategory_1: 'cap',
        subcategory_2: 'slate_cap'
    },
    {
        id: '10',
        name: 'Ящик Bearsbox',
        price: 100,
        depth: '33 см.',
        width: '33 см.',
        height: '38 см.',
        spaciousness: '40 л.',
        material: 'берёза',
        coating: 'восковый лак',
        description: `Ящик Bearsbox для детской! Компактно вместят детские игрушки, 
        материалы для творчества, книг и многое другое.Они легко и просто ...`,
        img: './img/bearsbox.png',
        img1: './img/bearsbox.png',
        img2: './img/bearsbox.jpg',
        img3: './img/bearsbox.jpg',
        img4: './img/bearsbox.jpg',
        category: 'Ящики для игрушек',
        subcategory_1: 'rest_box',
        subcategory_2: 'no_frame'
    },
    {
        id: '11',
        name: 'Ящик Pine Box',
        price: 29,
        depth: '40 см.',
        width: '30 см.',
        height: '15 см.',
        spaciousness: '20 л.',
        material: 'сосна',
        coating: '-',
        description: `Ящики из сосны для детской! Компактно вмещают детские игрушки, материалы для творчества,
        книги и многое другое. Они легко и просто становятся друг на друга, и не занимают много места!
        Экологичность и качество порадуют вас! Для удобства на ящиках установлены меловые таблички, которые
        подскажут что где лежит!`,
        img: './img/Pine.jpg',
        img1: './img/Pine.jpg',
        img2: './img/Pine.jpg',
        img3: './img/Pine.jpg',
        img4: './img/Pine.jpg',
        category: 'Ящики для игрушек',
        subcategory_1: 'rest_box',
        subcategory_2: 'frame'
    },
    {
        id: '12',
        name: 'Карандашница - Домик',
        price: 36,
        depth: '13 см.',
        width: '10 см.',
        height: '20 см.',
        spaciousness: '-',
        material: 'берёза',
        coating: 'восковый лак',
        description: `Карандашница-домик вместительная и стильная! Имеет два деления,
        для сортировки карандашей от фломастеров,ручек или кисточек и т.п.`,
        img: './img/karandasnica.jpg',
        img1: './img/karandasnica.jpg',
        img2: './img/karandasnica.jpg',
        img3: './img/karandasnica.jpg',
        img4: './img/karandasnica.jpg',
        category: 'Остальные товары',
        subcategory_1: 'pencil_box',
    },
    {
        id: '13',
        name: 'Карандашница - Бамбук',
        price: 30,
        depth: '10 см.',
        width: '10 см.',
        height: '20 см.',
        spaciousness: '-',
        material: 'бамбук',
        coating: '-',
        description: `Карандашница-домик вместительная и стильная! Имеет два деления,
        для сортировки карандашей от фломастеров,ручек или кисточек и т.п.`,
        img: './img/karandasnica_3.jpg',
        img1: './img/karandasnica_3.jpg',
        img2: './img/karandasnica_3.jpg',
        img3: './img/karandasnica_3.jpg',
        img4: './img/karandasnica_3.jpg',
        category: 'Остальные товары',
        subcategory_1: 'pencil_box',
    },
    {
        id: '14',
        name: 'Карандашница - 5 пород',
        price: 45,
        depth: '10 см.',
        width: '10 см.',
        height: '20 см.',
        spaciousness: '-',
        material: '5 пород',
        coating: '-',
        description: `Карандашница-домик вместительная и стильная! Имеет два деления,
        для сортировки карандашей от фломастеров,ручек или кисточек и т.п.`,
        img: './img/karandashnica_5.jpg',
        img1: './img/karandashnica_5.jpg',
        img2: './img/karandashnica_5.jpg',
        img3: './img/karandashnica_5.jpg',
        img4: './img/karandashnica_5.jpg',
        category: 'Остальные товары',
        subcategory_1: 'pencil_box',
    },
    {
        id: '15',
        name: 'Стеллаж открытый',
        price: 90,
        depth: '70 см.',
        width: '34 см.',
        height: '24,5 см.',
        spaciousness: '60 л.',
        material: 'берёза',
        coating: 'восковый лак',
        description: `Стеллажи модульные для детской! Компактно вместят детские игрушки, 
        материалы для творчества, книг и многое другое.Они легко и просто ...`,
        img: './img/open.jpg',
        img1: './img/open.jpg',
        img2: './img/open.jpg',
        img3: './img/open.jpg',
        img4: './img/open.jpg',
        category: 'Стеллажи и полки',
        subcategory_1: 'rack',
        subcategory_2: 'open'
    },
    {
        id: '16',
        name: 'Стеллаж с делениями',
        price: 100,
        depth: '70 см.',
        width: '34 см.',
        height: '24,5 см.',
        spaciousness: '60 л.',
        material: 'берёза',
        coating: 'восковый лак',
        description: `Стеллажи модульные для детской! Компактно вместят детские игрушки, 
        материалы для творчества, книг и многое другое.Они легко и просто ...`,
        img: './img/sdel.jpg',
        img1: './img/sdel.jpg',
        img2: './img/sdel.jpg',
        img3: './img/sdel.jpg',
        img4: './img/sdel.jpg',
        category: 'Стеллажи и полки',
        subcategory_1: 'rack',
        subcategory_2: 'with_divisions'
    },
    {
        id: '17',
        name: 'Стеллаж закрытый',
        price: 94,
        depth: '70 см.',
        width: '34 см.',
        height: '24,5 см.',
        spaciousness: '60 л.',
        material: 'берёза',
        coating: 'восковый лак',
        description: `Стеллажи модульные для детской! Компактно вместят детские игрушки, 
        материалы для творчества, книг и многое другое.Они легко и просто ...`,
        img: './img/clouse.jpg',
        img1: './img/clouse.jpg',
        img2: './img/clouse.jpg',
        img3: './img/clouse.jpg',
        img4: './img/clouse.jpg',
        category: 'Стеллажи и полки',
        subcategory_1: 'rack',
        subcategory_2: 'close'
    },
    {
        id: '18',
        name: 'Полка для книг Book-floor',
        price: 120,
        depth: '58 см.',
        width: '32 см.',
        height: '67 см.',
        spaciousness: '-',
        material: 'берёза',
        coating: 'восковый лак',
        description: `Напольная полка для книг - удобное место для хранения любимых книг
        и стильный аксессуар в детской комнате. Полка подходит для хранения как маленьких так и больших книг.`,
        img: './img/book_floor.png',
        img1: './img/book_floor.png',
        img2: './img/book_floor.png',
        img3: './img/book_floor.png',
        img4: './img/book_floor.png',
        category: 'Стеллажи и полки',
        subcategory_1: 'shelf',
        subcategory_2: 'outdoor'
    },
    {
        id: '19',
        name: 'Полка для книг Book-wall',
        price: 110,
        depth: '58 см.',
        width: '11 см.',
        height: '120 см.',
        spaciousness: '-',
        material: 'берёза',
        coating: 'восковый лак',
        description: `Подвесная полка для книг, станет отличным решением для детской - любимые книги
        Вашего малыша будут всегда на виду и под рукой. Полка крепиться к стене с помощью мебельных навесов.`,
        img: './img/book_wall.png',
        img1: './img/book_wall.png',
        img2: './img/book_wall.png',
        img3: './img/book_wall.png',
        img4: './img/book_wall.png',
        category: 'Стеллажи и полки',
        subcategory_1: 'shelf',
        subcategory_2: 'wall_mounted'
    },
    {
        id: '20',
        name: 'Грифельная доска-домик',
        price: 70,
        depth: '75 см.',
        width: '2 см.',
        height: '125 см.',
        spaciousness: '-',
        material: 'берёза',
        coating: 'грифельная эмаль',
        description: `Грифельная меловая доска в детскую!
        Если Ваш ребенок любит рисовать, то грифельная доска самое верное решение. С правой стороны
        у этого домика есть полочка, на которую очень удобно можно положить разноцветные мелки!`,
        img: './img/grif.jpg',
        img1: './img/grif.jpg',
        img2: './img/grif.jpg',
        img3: './img/grif.jpg',
        img4: './img/grif.jpg',
        category: 'Грифельные доски',
        subcategory_1: 'no_magnetic',
        subcategory_2: 'big_board',
    },
    {
        id: '21',
        name: 'Грифельная доска-ракета',
        price: 90,
        depth: '80 см.',
        width: '2 см.',
        height: '130 см.',
        spaciousness: '-',
        material: 'берёза',
        coating: 'грифельная эмаль',
        description: `Грифельная меловая доска в детскую!
        Если Ваш ребенок любит рисовать, то грифельная доска самое верное решение. С правой стороны
        у этого домика есть полочка, на которую очень удобно можно положить разноцветные мелки!`,
        img: './img/raketa.jpg',
        img1: './img/raketa.jpg',
        img2: './img/raketa.jpg',
        img3: './img/raketa.jpg',
        img4: './img/raketa.jpg',
        category: 'Грифельные доски',
        subcategory_1: 'no_magnetic',
        subcategory_2: 'big_board',
    },
    {
        id: '22',
        name: 'Грифильная доска - звезда',
        price: 50,
        depth: '50 см.',
        width: '1 см.',
        height: '50 см.',
        spaciousness: '-',
        material: 'берёза',
        coating: 'грифельная эмаль',
        description: `Грифельная меловая доска в детскую!
        Если Ваш ребенок любит рисовать, то грифельная доска самое верное решение. С правой стороны
        у этого домика есть полочка, на которую очень удобно можно положить разноцветные мелки!`,
        img: './img/grifStarbd.jpg',
        img1: './img/grifStarbd.jpg',
        img2: './img/grifStarbd.jpg',
        img3: './img/grifStarbd.jpg',
        img4: './img/grifStarbd.jpg',
        category: 'Грифельные доски',
        subcategory_1: 'magnetic',
        subcategory_2: 'small_board',
    },
    {
        id: '23',
        name: 'Грифильная доска - шар',
        price: 46,
        depth: '50 см.',
        width: '1 см.',
        height: '80 см.',
        spaciousness: '-',
        material: 'берёза',
        coating: 'грифельная эмаль',
        description: `Грифельная меловая доска в детскую!
        Если Ваш ребенок любит рисовать, то грифельная доска самое верное решение. С правой стороны
        у этого домика есть полочка, на которую очень удобно можно положить разноцветные мелки!`,
        img: './img/grifShar.jpg',
        img1: './img/grifShar.jpg',
        img2: './img/grifShar.jpg',
        img3: './img/grifShar.jpg',
        img4: './img/grifShar.jpg',
        category: 'Грифельные доски',
        subcategory_1: 'no_magnetic',
        subcategory_2: 'small_board',
    },
    {
        id: '24',
        name: 'Грифильная доска - сова',
        price: 40,
        depth: '60 см.',
        width: '1 см.',
        height: '60 см.',
        spaciousness: '-',
        material: 'берёза',
        coating: 'грифельная эмаль',
        description: `Грифельная меловая доска в детскую!
        Если Ваш ребенок любит рисовать, то грифельная доска самое верное решение. С правой стороны
        у этого домика есть полочка, на которую очень удобно можно положить разноцветные мелки!`,
        img: './img/grisSova.jpg',
        img1: './img/grisSova.jpg',
        img2: './img/grisSova.jpg',
        img3: './img/grisSova.jpg',
        img4: './img/grisSova.jpg',
        category: 'Грифельные доски',
        subcategory_1: 'magnetic',
        subcategory_2: 'small_board',
    },
    {
        id: '25',
        name: 'Грифельная доска-класик',
        price: 50,
        depth: '60 см.',
        width: '1 см.',
        height: '100 см.',
        spaciousness: '-',
        material: 'берёза',
        coating: 'грифельная эмаль',
        description: `Грифельная меловая доска в детскую!
        Если Ваш ребенок любит рисовать, то грифельная доска самое верное решение. С правой стороны
        у этого домика есть полочка, на которую очень удобно можно положить разноцветные мелки!`,
        img: './img/grifclas.jpg',
        img1: './img/grifclas.jpg',
        img2: './img/grifclas.jpg',
        img3: './img/grifclas.jpg',
        img4: './img/grifclas.jpg',
        category: 'Грифельные доски',
        subcategory_1: 'no_magnetic',
        subcategory_2: 'small_board',
    },
    {
        id: '26',
        name: 'Игрушечный буфет',
        price: 40,
        depth: '10 см.',
        width: '15 см.',
        height: '20 см.',
        spaciousness: '-',
        material: 'берёза',
        coating: 'восковый лак',
        description: `Мы знаем как важно прививать вкус к эстетике с ранних лет, по этому создаем стильные
        и красивые вещи. Сегодня мы хотим представить вам кукольный буфет из новой серии "retro doll house"
        - выполненный вручную из экологически чистого материала - дерева.Игрушечная мебель подарит много
        радости вашему ребенку и может навсегда остаться теплым воспоминанием из детства. Bearsbox- мебель
        созданная с душой!`,
        img: './img/bufet.jpg',
        img1: './img/bufet.jpg',
        img2: './img/bufet.jpg',
        img3: './img/bufet.jpg',
        img4: './img/bufet.jpg',
        category: 'Остальные товары',
        subcategory_1: 'toy_furniture',
    },
    {
        id: '27',
        name: 'Игрушечная кровать ',
        price: 50,
        depth: '10 см.',
        width: '40 см.',
        height: '20 см.',
        spaciousness: '-',
        material: 'берёза',
        coating: 'восковый лак',
        description: `Эта серия домиков будет поступать в продажу небольшими партиями, и продаваться 
        только по наличию. Как скоро поступит следующая партия к сожалению не известно и зависит 
        только он нашего драгоценного мастера с золотыми руками `,
        img: './img/krovat.jpg',
        img1: './img/krovat.jpg',
        img2: './img/krovat.jpg',
        img3: './img/krovat.jpg',
        img4: './img/krovat.jpg',
        category: 'Остальные товары',
        subcategory_1: 'toy_furniture'
    },
    {
        id: '28',
        name: 'Игрушечные стол, стулья',
        price: 30,
        depth: '10 см.',
        width: '20 см.',
        height: '10 см.',
        spaciousness: '-',
        material: 'берёза',
        coating: 'восковый лак',
        description: `В комплект входят игрушечный стол и два стульчика, расцветку 
        стульев можно выбрать в нашей палитре.`,
        img: './img/stol.jpg',
        img1: './img/stol.jpg',
        img2: './img/stol.jpg',
        img3: './img/stol.jpg',
        img4: './img/stol.jpg',
        category: 'Остальные товары',
        subcategory_1: 'toy_furniture'
    },
    {
        id: '29',
        name: 'Колесики',
        price: 15,
        depth: '5 см.',
        width: '5 см.',
        height: '5 см.',
        spaciousness: '-',
        material: '-',
        coating: '-',
        description: `Колесики для ящиков и стеллажей!`,
        img: './img/kalesa.png',
        img1: './img/kalesa.png',
        img2: './img/kalesa.png',
        img3: './img/kalesa.png',
        img4: './img/kalesa.png',
        category: 'Остальные товары',
        subcategory_1: 'furniture'
    },
    {
        id: '30',
        name: 'Подвесы мебельные',
        price: 5,
        depth: '1 см.',
        width: '2 см.',
        height: '5 см.',
        spaciousness: '-',
        material: '-',
        coating: '-',
        description: `Навесы для досок и настенной полки`,
        img: './img/pod.jpg',
        img1: './img/pod.jpg',
        img2: './img/pod.jpg',
        img3: './img/pod.jpg',
        img4: './img/pod.jpg',
        category: 'Остальные товары',
        subcategory_1: 'furniture'
    },
    {
        id: '31',
        name: 'Мелки',
        price: 5,
        price: '5',
        depth: '10 см.',
        width: '2 см.',
        height: '5 см.',
        spaciousness: '-',
        material: '-',
        coating: '-',
        description: `Мелки для грифельных досок крышек и рамок`,
        img: './img/melki.jpg',
        img1: './img/melki.jpg',
        img2: './img/melki.jpg',
        img3: './img/melki.jpg',
        img4: './img/melki.jpg',
        category: 'Остальные товары',
        subcategory_1: 'crayons'
    }
]