const catalogProduct = [
    {
        id: '1',
        name: 'Box Optima',
        price: 72,
        depth: '34 cm.',
        width: '32 cm.',
        height: '24,5 cm.',
        spaciousness: '27 l.',
        material: 'birch tree',
        coating: 'wax varnish',
        description: `Modular boxes for children! Compactly accommodate children's toys, materials for creativity,
        books and much more.They easily and simply become on each other, and do not take up much space!<br><br>
       In our palette, you will be sure to choose the right colors of boxes in your nursery, and the chalk plate will tell you,
       what and where is!<br>`,
        img: '../img/optima.jpg',
        img1: '../img/optima.jpg',
        img2: '../img/img_product/C4zuU3NFOCM.jpg',
        img3: '../img/img_product/r7VvMGAQluc.jpg',
        img4: '../img/img_product/m7qbZc8EfJA.jpg',
        category: 'Ящики для игрушек',
        subcategory_1: 'modular',
        subcategory_2: 'frame'
    },
    {
        id: '2',
        name: 'Box Maxi',
        price: ((80 / 100) * 80).toFixed(0),
        depth: '34 cm.',
        width: '32 cm.',
        height: '37 cm.',
        spaciousness: '40 l.',
        material: 'birch tree',
        coating: 'wax varnish',
        description: `Modular boxes for children! Compactly accommodate children's toys, materials for creativity,
        books and much more.They easily and simply become on each other, and do not take up much space!<br><br>
       In our palette, you will be sure to choose the right colors of boxes in your nursery, and the chalk plate will tell you,
       what and where is!<br>`,
        img: '../img/maxi.jpg',
        img1: '../img/maxi.jpg',
        img2: '../img/img_product/69514036_355147265365419_7233966578354388877_n.jpg',
        img3: '../img/img_product/RT_E_kWPzWA.jpg',
        img4: '../img/img_product/-TUAkI9kkoI.jpg',
        category: 'Ящики для игрушек',
        subcategory_1: 'modular',
        subcategory_2: 'frame'
    },
    {
        id: '3',
        name: 'Lid for drawers',
        price: ((26 / 100) * 80).toFixed(0),
        depth: '34 cm.',
        width: '32 cm.',
        height: '5 cm.',
        spaciousness: '-',
        material: 'birch tree',
        coating: 'wax varnish',
        description: `The lid is placed on the drawers: mini, optima, maxi`,
        img: '../img/krisha.jpg',
        img1: '../img/krisha.jpg',
        img2: '../img/img_product/03V4cIQXia4.jpg',
        img3: '../img/img_product/IUm_j8RYeC4.jpg',
        img4: '../img/img_product/h3l2DfI_rNE.jpg',
        category: 'Ящики для игрушек',
        subcategory_1: 'cap',
        subcategory_2: 'no_slate_cap'
    },
    {
        id: '4',
        name: 'Box Mini',
        price: ((60 / 100) * 80).toFixed(0),
        depth: '34 cm.',
        width: '32 cm.',
        height: '12,5 cm.',
        spaciousness: '13 l.',
        material: 'birch tree',
        coating: 'wax varnish',
        description: `Modular boxes for children! Compactly accommodate children's toys, 
        materials for creativity, books, and more.They are easy and simple ...`,
        img: '../img/mini.png',
        img1: '../img/mini.png',
        img2: '../img/img_product/отобр8.jpg',
        img3: '../img/img_product/DSC02603.jpg',
        img4: '../img/img_product/69514036_355147265365419_7233966578354388877_n.jpg',
        category: 'Ящики для игрушек',
        subcategory_1: 'modular',
        subcategory_2: 'no_frame'
    },
    {
        id: '5',
        name: 'Mini box with divisions',
        price: ((66 / 100) * 80).toFixed(0),
        depth: '34 cm.',
        width: '32 cm.',
        height: '12,5 cm.',
        spaciousness: '13 l.',
        material: 'birch tree',
        coating: 'wax varnish',
        description: `Modular boxes for children! Compactly accommodate children's toys, 
        materials for creativity, books, and more.They are easy and simple ...`,
        img: '../img/minidel.jpg',
        img1: '../img/minidel.jpg',
        img2: '../img/img_product/DSC_93191567.jpg',
        img3: '../img/img_product/DSC02603.jpg',
        img4: '../img/img_product/-TUAkI9kkoI.jpg',
        category: 'Ящики для игрушек',
        subcategory_1: 'modular',
        subcategory_2: 'no_frame'
    },
    {
        id: '6',
        name: 'Cover for Mini',
        price: ((14 / 100) * 80).toFixed(0),
        depth: '34 cm.',
        width: '32 cm.',
        height: '1 cm.',
        spaciousness: '-',
        material: 'birch tree',
        coating: 'wax varnish',
        description: `Cover for the "Mini" box with divisions"`,
        img: '../img/krishmini.jpg',
        img1: '../img/krishmini.jpg',
        img2: '../img/krishmini.jpg',
        img3: '../img/krishmini.jpg',
        img4: '../img/krishmini.jpg',
        category: 'Ящики для игрушек',
        subcategory_1: 'cap',
        subcategory_2: 'slate_cap'
    },
    {
        id: '7',
        name: 'Box Huge',
        price: ((70 / 100) * 80).toFixed(0),
        depth: '60 cm.',
        width: '60 cm.',
        height: '15 cm.',
        spaciousness: '48 l.',
        material: 'birch tree',
        coating: 'wax varnish',
        description: `Modular boxes for children! Compactly accommodate children's toys, 
        materials for creativity, books, and more.They are easy and simple ...`,
        img: '../img/huge.jpg',
        img1: '../img/huge.jpg',
        img2: '../img/huge.jpg',
        img3: '../img/huge.jpg',
        img4: '../img/huge.jpg',
        category: 'Ящики для игрушек',
        subcategory_1: 'big',
        subcategory_2: 'frame'
    },
    {
        id: '8',
        name: 'Huge box with divisions',
        price: 80,
        depth: '60 cm.',
        width: '60 cm.',
        height: '15 cm.',
        spaciousness: '48 l.',
        material: 'birch tree',
        coating: 'wax varnish',
        description: `Modular boxes for children! Compactly accommodate children's toys, 
        materials for creativity, books, and more.They are easy and simple ...`,
        img: '../img/hugedel.jpg',
        img1: '../img/hugedel.jpg',
        img2: '../img/hugedel.jpg',
        img3: '../img/hugedel.jpg',
        img4: '../img/hugedel.jpg',
        category: 'Ящики для игрушек',
        subcategory_1: 'big',
        subcategory_2: 'frame'
    },
    {
        id: '9',
        name: 'Cover for Huge',
        price: 26,
        depth: '60 cm.',
        width: '60 cm.',
        height: '1 cm.',
        spaciousness: '-',
        material: 'birch tree',
        coating: 'wax varnish',
        description: `Cover for the "Huge" box with divisions"!!!`,
        img: '../img/krishhuge.jpg',
        img1: '../img/krishhuge.jpg',
        img2: '../img/krishhuge.jpg',
        img3: '../img/krishhuge.jpg',
        img4: '../img/krishhuge.jpg',
        category: 'Ящики для игрушек',
        subcategory_1: 'cap',
        subcategory_2: 'slate_cap'
    },
    {
        id: '10',
        name: 'Box Bearsbox',
        price: 100,
        depth: '33 cm.',
        width: '33 cm.',
        height: '38 cm.',
        spaciousness: '40 l.',
        material: 'birch tree',
        coating: 'wax varnish',
        description: `Box Bearsbox for children! Compactly accommodate children's toys, 
        materials for creativity, books, and more.They are easy and simple ...`,
        img: '../img/bearsbox.png',
        img1: '../img/bearsbox.png',
        img2: '../img/bearsbox.jpg',
        img3: '../img/bearsbox.jpg',
        img4: '../img/bearsbox.jpg',
        category: 'Ящики для игрушек',
        subcategory_1: 'rest_box',
        subcategory_2: 'no_frame'
    },
    {
        id: '11',
        name: 'Pine Box',
        price: 29,
        depth: '40 cm.',
        width: '30 cm.',
        height: '15 cm.',
        spaciousness: '20 l.',
        material: 'pine',
        coating: '-',
        description: `Pine boxes for the nursery! Compactly accommodate children's toys, materials for creativity,
        books and more. They easily and simply become on each other, and do not take up much space!
        Environmental friendliness and quality will please you! For convenience, the boxes are equipped with chalk signs that
        tell me what is where!`,
        img: '../img/Pine.jpg',
        img1: '../img/Pine.jpg',
        img2: '../img/Pine.jpg',
        img3: '../img/Pine.jpg',
        img4: '../img/Pine.jpg',
        category: 'Ящики для игрушек',
        subcategory_1: 'rest_box',
        subcategory_2: 'frame'
    },
    {
        id: '12',
        name: 'Pencil Box-House',
        price: 36,
        depth: '13 cm.',
        width: '10 cm.',
        height: '20 cm.',
        spaciousness: '-',
        material: 'birch tree',
        coating: 'wax varnish',
        description: `Pencil box-house roomy and stylish! It has two divisions,
        for sorting pencils from markers, pens or brushes, etc..`,
        img: '../img/karandasnica.jpg',
        img1: '../img/karandasnica.jpg',
        img2: '../img/karandasnica.jpg',
        img3: '../img/karandasnica.jpg',
        img4: '../img/karandasnica.jpg',
        category: 'Остальные товары',
        subcategory_1: 'pencil_box',
    },
    {
        id: '13',
        name: 'Pencil Holder-Bamboo',
        price: 30,
        depth: '10 cm.',
        width: '10 cm.',
        height: '20 cm.',
        spaciousness: '-',
        material: 'bamboo',
        coating: '-',
        description: `Pencil box-house roomy and stylish! It has two divisions,
        for sorting pencils from markers, pens or brushes, etc.`,
        img: '../img/karandasnica_3.jpg',
        img1: '../img/karandasnica_3.jpg',
        img2: '../img/karandasnica_3.jpg',
        img3: '../img/karandasnica_3.jpg',
        img4: '../img/karandasnica_3.jpg',
        category: 'Остальные товары',
        subcategory_1: 'pencil_box',
    },
    {
        id: '14',
        name: 'Pencil box - 5 breeds',
        price: 45,
        depth: '10 cm.',
        width: '10 cm.',
        height: '20 cm.',
        spaciousness: '-',
        material: '5 breeds',
        coating: '-',
        description: `Pencil box-house roomy and stylish! It has two divisions,
        for sorting pencils from markers, pens or brushes, etc..`,
        img: '../img/karandashnica_5.jpg',
        img1: '../img/karandashnica_5.jpg',
        img2: '../img/karandashnica_5.jpg',
        img3: '../img/karandashnica_5.jpg',
        img4: '../img/karandashnica_5.jpg',
        category: 'Остальные товары',
        subcategory_1: 'pencil_box',
    },
    {
        id: '15',
        name: 'Open rack',
        price: 90,
        depth: '70 cm.',
        width: '34 cm.',
        height: '24,5 cm.',
        spaciousness: '60 l.',
        material: 'birch tree',
        coating: 'wax varnish',
        description: `The modular shelving for the nursery! Compactly accommodate children's toys, 
        creative materials, books, and more.They are easy and simple ...`,
        img: '../img/open.jpg',
        img1: '../img/open.jpg',
        img2: '../img/open.jpg',
        img3: '../img/open.jpg',
        img4: '../img/open.jpg',
        category: 'Стеллажи и полки',
        subcategory_1: 'rack',
        subcategory_2: 'open'
    },
    {
        id: '16',
        name: 'Rack with divisions',
        price: 100,
        depth: '70 cm.',
        width: '34 cm.',
        height: '24,5 cm.',
        spaciousness: '60 l.',
        material: 'birch tree',
        coating: 'wax varnish',
        description: `The modular shelving for the nursery! Compactly accommodate children's toys, 
        creative materials, books, and more.They are easy and simple ...`,
        img: '../img/sdel.jpg',
        img1: '../img/sdel.jpg',
        img2: '../img/sdel.jpg',
        img3: '../img/sdel.jpg',
        img4: '../img/sdel.jpg',
        category: 'Стеллажи и полки',
        subcategory_1: 'rack',
        subcategory_2: 'with_divisions'
    },
    {
        id: '17',
        name: 'Rack is closed',
        price: 94,
        depth: '70 cm.',
        width: '34 cm.',
        height: '24,5 cm.',
        spaciousness: '60 l.',
        material: 'birch tree',
        coating: 'wax varnish',
        description: `The modular shelving for the nursery! Compactly accommodate children's toys, 
        creative materials, books, and more.They are easy and simple ...`,
        img: '../img/clouse.jpg',
        img1: '../img/clouse.jpg',
        img2: '../img/clouse.jpg',
        img3: '../img/clouse.jpg',
        img4: '../img/clouse.jpg',
        category: 'Стеллажи и полки',
        subcategory_1: 'rack',
        subcategory_2: 'close'
    },
    {
        id: '18',
        name: 'Shelf for books Book-floor',
        price: 120,
        depth: '58 cm.',
        width: '32 cm.',
        height: '67 cm.',
        spaciousness: '-',
        material: 'birch tree',
        coating: 'wax varnish',
        description: `Floor shelf for books - a convenient place to store your favorite books
        and a stylish accessory in the children's room. The shelf is suitable for storing both small and large books.`,
        img: '../img/book_floor.png',
        img1: '../img/book_floor.png',
        img2: '../img/book_floor.png',
        img3: '../img/book_floor.png',
        img4: '../img/book_floor.png',
        category: 'Стеллажи и полки',
        subcategory_1: 'shelf',
        subcategory_2: 'outdoor'
    },
    {
        id: '19',
        name: 'Shelf for books Book-wall',
        price: 110,
        depth: '58 cm.',
        width: '11 cm.',
        height: '120 cm.',
        spaciousness: '-',
        material: 'birch tree',
        coating: 'wax varnish',
        description: `Hanging shelf for books, will be a great solution for children's-favorite books
        Your baby will always be in sight and at hand. The shelf is attached to the wall using furniture canopies.`,
        img: '../img/book_wall.png',
        img1: '../img/book_wall.png',
        img2: '../img/book_wall.png',
        img3: '../img/book_wall.png',
        img4: '../img/book_wall.png',
        category: 'Стеллажи и полки',
        subcategory_1: 'shelf',
        subcategory_2: 'wall_mounted'
    },
    {
        id: '20',
        name: 'Slate-house',
        price: 70,
        depth: '75 cm.',
        width: '2 cm.',
        height: '125 cm.',
        spaciousness: '-',
        material: 'birch tree',
        coating: 'slate enamel',
        description: `Slate chalk Board in the nursery!
        If Your child likes to draw, then a slate is the right solution. On the right
        this house has a shelf, which is very convenient to put colored crayons!`,
        img: '../img/grif.jpg',
        img1: '../img/grif.jpg',
        img2: '../img/grif.jpg',
        img3: '../img/grif.jpg',
        img4: '../img/grif.jpg',
        category: 'Грифельные доски',
        subcategory_1: 'no_magnetic',
        subcategory_2: 'big_board',
    },
    {
        id: '21',
        name: 'Slate-rocket',
        price: 90,
        depth: '80 cm.',
        width: '2 cm.',
        height: '130 cm.',
        spaciousness: '-',
        material: 'birch tree',
        coating: 'slate enamel',
        description: `Slate chalk Board in the nursery!
        If Your child likes to draw, then a slate is the right solution. On the right
        from this house there is a shelf that is very convenient to put the colored crayons!`,
        img: '../img/raketa.jpg',
        img1: '../img/raketa.jpg',
        img2: '../img/raketa.jpg',
        img3: '../img/raketa.jpg',
        img4: '../img/raketa.jpg',
        category: 'Грифельные доски',
        subcategory_1: 'no_magnetic',
        subcategory_2: 'big_board',
    },
    {
        id: '22',
        name: 'Slate-star',
        price: 50,
        depth: '50 cm.',
        width: '1 cm.',
        height: '50 cm.',
        spaciousness: '-',
        material: 'birch tree',
        coating: 'slate enamel',
        description: `Slate chalk Board in the nursery!
        If Your child likes to draw, then a slate is the right solution. On the right
        this house has a shelf, which is very convenient to put colored crayons!`,
        img: '../img/grifStarbd.jpg',
        img1: '../img/grifStarbd.jpg',
        img2: '../img/grifStarbd.jpg',
        img3: '../img/grifStarbd.jpg',
        img4: '../img/grifStarbd.jpg',
        category: 'Грифельные доски',
        subcategory_1: 'magnetic',
        subcategory_2: 'small_board',
    },
    {
        id: '23',
        name: 'Slate-ball',
        price: 46,
        depth: '50 cm.',
        width: '1 cm.',
        height: '80 cm.',
        spaciousness: '-',
        material: 'birch tree',
        coating: 'slate enamel',
        description: `Slate chalk Board in the nursery!
        If Your child likes to draw, then a slate is the right solution. On the right
        from this house there is a shelf that is very convenient to put the colored crayons!`,
        img: '../img/grifShar.jpg',
        img1: '../img/grifShar.jpg',
        img2: '../img/grifShar.jpg',
        img3: '../img/grifShar.jpg',
        img4: '../img/grifShar.jpg',
        category: 'Грифельные доски',
        subcategory_1: 'no_magnetic',
        subcategory_2: 'small_board',
    },
    {
        id: '24',
        name: 'Slate-owl',
        price: 40,
        depth: '60 cm.',
        width: '1 cm.',
        height: '60 cm.',
        spaciousness: '-',
        material: 'birch tree',
        coating: 'slate enamel',
        description: `Slate chalk Board in the nursery!
        If Your child likes to draw, then a slate is the right solution. On the right
        from this house there is a shelf that is very convenient to put the colored crayons!`,
        img: '../img/grisSova.jpg',
        img1: '../img/grisSova.jpg',
        img2: '../img/grisSova.jpg',
        img3: '../img/grisSova.jpg',
        img4: '../img/grisSova.jpg',
        category: 'Грифельные доски',
        subcategory_1: 'magnetic',
        subcategory_2: 'small_board',
    },
    {
        id: '25',
        name: 'Slate-classic',
        price: 50,
        depth: '60 cm.',
        width: '1 cm.',
        height: '100 cm.',
        spaciousness: '-',
        material: 'birch tree',
        coating: 'slate enamel',
        description: `Slate chalk Board in the nursery!
        If Your child likes to draw, then a slate is the right solution. On the right
        from this house there is a shelf that is very convenient to put the colored crayons!`,
        img: '../img/grifclas.jpg',
        img1: '../img/grifclas.jpg',
        img2: '../img/grifclas.jpg',
        img3: '../img/grifclas.jpg',
        img4: '../img/grifclas.jpg',
        category: 'Грифельные доски',
        subcategory_1: 'no_magnetic',
        subcategory_2: 'small_board',
    },
    {
        id: '26',
        name: 'Toy buffet',
        price: 40,
        depth: '10 cm.',
        width: '15 cm.',
        height: '20 cm.',
        spaciousness: '-',
        material: 'birch tree',
        coating: 'wax varnish',
        description: `We know how important it is to instill a taste for aesthetics from an early age, so we create stylish
        and beautiful things. Today we want to present you a doll buffet from the new series " retro doll house"
        - made by hand from an environmentally friendly material-wood.Toy furniture will give a lot
        joy to your child and can always remain a warm memory from childhood. Bearsbox-furniture
        created with a soul!`,
        img: '../img/bufet.jpg',
        img1: '../img/bufet.jpg',
        img2: '../img/bufet.jpg',
        img3: '../img/bufet.jpg',
        img4: '../img/bufet.jpg',
        category: 'Остальные товары',
        subcategory_1: 'toy_furniture',
    },
    {
        id: '27',
        name: 'Toy bed ',
        price: 50,
        depth: '10 cm.',
        width: '40 cm.',
        height: '20 cm.',
        spaciousness: '-',
        material: 'birch tree',
        coating: 'wax varnish',
        description: `This series of houses will go on sale in small batches, and will be sold 
        only by availability. How soon the next batch will arrive unfortunately is not known and depends 
        only he is our precious master with Golden hands `,
        img: '../img/krovat.jpg',
        img1: '../img/krovat.jpg',
        img2: '../img/krovat.jpg',
        img3: '../img/krovat.jpg',
        img4: '../img/krovat.jpg',
        category: 'Остальные товары',
        subcategory_1: 'toy_furniture'
    },
    {
        id: '28',
        name: 'Toy table, chairs',
        price: 30,
        depth: '10 cm.',
        width: '20 cm.',
        height: '10 cm.',
        spaciousness: '-',
        material: 'birch tree',
        coating: 'wax varnish',
        description: `The set includes a toy table and two chairs, colors 
        chairs can be selected in our palette.`,
        img: '../img/stol.jpg',
        img1: '../img/stol.jpg',
        img2: '../img/stol.jpg',
        img3: '../img/stol.jpg',
        img4: '../img/stol.jpg',
        category: 'Остальные товары',
        subcategory_1: 'toy_furniture'
    },
    {
        id: '29',
        name: 'Castors',
        price: 15,
        depth: '5 cm.',
        width: '5 cm.',
        height: '5 cm.',
        spaciousness: '-',
        material: '-',
        coating: '-',
        description: `Wheels for drawers and racks!`,
        img: '../img/kalesa.png',
        img1: '../img/kalesa.png',
        img2: '../img/kalesa.png',
        img3: '../img/kalesa.png',
        img4: '../img/kalesa.png',
        category: 'Остальные товары',
        subcategory_1: 'furniture'
    },
    {
        id: '30',
        name: 'Furniture suspensions',
        price: 5,
        depth: '1 cm.',
        width: '2 cm.',
        height: '5 cm.',
        spaciousness: '-',
        material: '-',
        coating: '-',
        description: `Canopies for boards and wall shelves`,
        img: '../img/pod.jpg',
        img1: '../img/pod.jpg',
        img2: '../img/pod.jpg',
        img3: '../img/pod.jpg',
        img4: '../img/pod.jpg',
        category: 'Остальные товары',
        subcategory_1: 'furniture'
    },
    {
        id: '31',
        name: 'Small',
        price: 5,
        price: '5',
        depth: '10 cm.',
        width: '2 cm.',
        height: '5 cm.',
        spaciousness: '-',
        material: '-',
        coating: '-',
        description: `Crayons for slates covers and frames`,
        img: '../img/melki.jpg',
        img1: '../img/melki.jpg',
        img2: '../img/melki.jpg',
        img3: '../img/melki.jpg',
        img4: '../img/melki.jpg',
        category: 'Остальные товары',
        subcategory_1: 'crayons'
    }
]